### ISSUE TITLE
Teste - Checar as páginas do ambiente de homologação x seeds

### ISSUE THREAD

**Issue by giordanasousa** [EscolaDeSaudePublica/registrocovid-api#125]
## Contexto
Durante os testes no ambiente de homologação, os usuários solicitaram alterações em alguns seeds, o que acarretou em divergência entre os seeds e o ambiente de homologação.

## Dentro do escopo
- Verificar se os seeds estão aparecendo direitinho nas páginas da aplicação que está no ambiente de homologação.

**Comment by FelipeSVidal** [comment]
| SEED | Problema | Página |
| ------ | ----------- | ------ |
| Categorias | História Pessoal não está no diagrama | Informações Gerais |
| Cores | Não estão exatamente iguais | Identificação do Paciente |
| Estados Civis | Há mais Estados que os listados no diagrama| Identificação do Paciente |
| Tipo Cuidado Paliativo | No diagrama tem Ordem de não ressuscitação e em homologação está Não RCP por gravidade do caso   | Desfecho |
