### ISSUE TITLE
[Back] Criar rota para trazer a data do último desfecho de um paciente

### ISSUE THREAD

**Issue by giordanasousa** [EscolaDeSaudePublica/registrocovid-api#128]
- Criar uma rota para trazer a data do último desfecho de um paciente (data do último desfecho é a data mais recente dentre todos os desfechos de um paciente).
- Caso não tenha nenhum desfecho cadastro pode retornar vazio.

- Essa rota será utilizada para as validações dos campos e regras de negócio, no frontend.

**Comment by FelipeSVidal** [comment]
| SEED | Problema | Página |
| ------ | ----------- | ------ |
| Categorias | História Pessoal não está no diagrama | Informações Gerais |
| Cores | Não estão exatamente iguais | Identificação do Paciente |
| Estados Civis | Há mais Estados que os listados no diagrama| Identificação do Paciente |
| Tipo Cuidado Paliativo | No diagrama tem Ordem de não ressuscitação e em homologação está Não RCP por gravidade do caso   | Desfecho |
