### ISSUE TITLE
[Back] Criação de endpoint para apagar dados inputados pelo usuário de teste - ambiente de produção

### ISSUE THREAD

**Issue by giordanasousa** [EscolaDeSaudePublica/registrocovid-api#132]
## Contexto
Um usuário de teste para o ambiente de produção foi criado, porém, os dados imputados por esse usuário não podem permanecer no banco de dados.

## Dentro do escopo
- Criar um endpoint para apagar os dados imputados por esse usuário de teste no banco de dados (aplicação em produção).

**Comment by FelipeSVidal** [comment]
Adicionar ao .env!
DUMMY_ID=5
