### ISSUE TITLE
Ajuste nos campos Varchar

### ISSUE THREAD

**Issue by giordanasousa** [EscolaDeSaudePublica/registrocovid-api#134]
## Contexto
Os campos Varchar estão permitindo a inclusão de apenas 191 caracteres, e alguns resultados de exames são maiores que isso. (exemplo, exames da página de Exames complementares)
Quando o coletador insere mais que os 191 caracteres, o sistema gera um erro e não salva as informações.

Erro retornado: `O campo examescomplementares.0.resultado não pode ser superior a 191 caracteres`

## Dentro do escopo
- Aumentar tamanho dos campos varchar onde são registrados resultados e descrições para 1000 caracteres.

**Comment by camilaccolares** [comment]
Campos alterados:
- complicacoes.descricao
- complicacoes_ventilacao_mec.descricao
- corticosteroides.descricao
- desfechos.causa_obito
- doencas.descricao

**Comment by ericsonmoreira** [comment]
@camilaccolares Já vou aproveitar e colocar essas validações no frontend.
