### ISSUE TITLE
[Back] Unificação da página de Exames Físicos com a página Suporte Respiratório

### ISSUE THREAD

**Issue by luannaalves** [EscolaDeSaudePublica/registrocovid-api#166]
## Contexto

   A coleta de dados sobre a utilização de suportes respiratórios é realizada diariamente e sofre alterações constantes, podendo ser estas no decorrer do dia ou da semana. Portanto, a inserção dessas informações de forma diária é mais valiosa para a realização das análises. Atualmente, a página de Suporte Respiratório colhe datas de inicio e término, sem levar em consideração a informação diária sobre o suporte utilizado pelos pacientes. 

## Dentro do escopo

- Tirar a obrigatoriedade do campo data_término da tabela de suporte_respiratório.
- Verificar a necessidade de renomear o campo data_inicio, pois a ideia é utilizar o mesmo campo de data da tabela de Exame físico para popular esse dado.
- Necessário modificar relação do Suporte Respiratório, que anteriormente era diretamente do paciente e passa a ser relacionada a data de evolução do id do paciente.
- Utiizar o mesmo endpoint e tabelas, alterando a origem da data de ocorrência (data de início), pois esta data deve ser obtida do campo Data de Evolução.
Obs.: Após alteração, criar Script (no Laravel) para atulizar as informações dos pacientes já cadastrados: Para todo paciente que possuir informação de data de término, deverá ser criada uma linha para cada dia de ocorrência dos seus respectivos suportes respiratórios.

### Critérios de Aceite

- [x] Tirar a obrigatoriedade do campo data_término da tabela de suporte_respiratório.
- [ ] Verificar a necessidade de renomear o campo data_inicio, pois a ideia é utilizar o mesmo campo de data da tabela de Exame físico para popular esse dado.
- [ ] Modificar relação do Suporte Respiratório, que passa a ser pela data de evolução do id do paciente.
- [ ] Utiizar o mesmo endpoint e tabelas, alterando a origem da data de ocorrência (data de início), pois esta data deve ser obtida do campo Data de Evolução.
- [x] Criar Script (no Laravel) para atulizar as informações dos pacientes já cadastrados: Para todo paciente que possuir informação de data de término, deverá ser criada uma linha para cada dia de ocorrência dos seus respectivos suportes respiratórios.

**Comment by FelipeSVidal** [comment]
### **Obrigatório o uso destes comandos:**
`php artisan db:seed --class=SituacaoTabagismoSeeder --force`
`php artisan db:seed --class=SituacaoEtilismoSeeder--force`

Adicionar em situacoes_uso_drogas nova linha com os seguintes dados:
['id' => 4, 'descricao' => 'Não Informado']
