### ISSUE TITLE
[Back] Verificação de bug de envio de informações para o front (incluir Não informado) - página Exames laboratoriais específicos da COVID19

### ISSUE THREAD

**Issue by luannaalves** [EscolaDeSaudePublica/registrocovid-api#189]
### Contexto
Após ajuste nas validações dos campos **Data de coleta RT-PCR, Sítio da Amostra RT-PCR, Data do Resultado RT-PCR e Resultado RT-PCR**, da página Exames laboratoriais específicos COVID 19, ao inserir dados, a página salva normalmente, porém o backend não está enviando as informações salvas para o front, apresentando um erro: que não tem permissão para abrir uma página a partir desta.

### Escopo
Devido as validações de **Data de coleta RT-PCR e Sítio da Amostra RT-PCR** terem sido para retirar a obrigatoriedade de preenchimento destes campos, e ainda os campos **Data do Resultado RT-PCR e Resultado RT-PCR** terem se tornado identificadores para salvamento desta página, é necessário verificar junto ao banco de dados se tais campos constam como obrigatórios e possam estar gerando este erro de envio de informações para o frontend. Todavia, deverá ser identificado o problema que está gerando este erro no backend.

**Após análise no backend foi identificado que o campo Sítio da amostra RT-PCR está como referência no laravel, permitindo salvar as informações desta página sem o preenchimento deste campo, porém não envia as informações para o front depois de salvas. Com isso, este campo será mantido como obrigatório, porém será incluída a opção de resposta Não Informado.**

### Critérios de Aceite
- [x] Incluir opção de resposta **Não Informado**, para Sítio da amostra RT-PCR no banco de dados
- [x] Enviar informação para o Front

**Comment by FelipeSVidal** [comment]
Vimos que o erro é causado pois o tipo de sitio é uma referencia, caso não passemos essa referencia causa erro no carregamento.
