### ISSUE TITLE
[Back] Bug no envio de datas salvas página suporte respiratório - Ambiente de Produção

### ISSUE THREAD

**Issue by luannaalves** [EscolaDeSaudePublica/registrocovid-api#200]
### Contexto
Na página **Suporte respiratório**, foi identificado um bug pelo Ambiente de produção, que após salvar um suporte respiratório com data de início de data de término, a informação da data de término não é mostrada no front, ficando o campo em branco.

### Escopo
Corrigir bug de envio de informações salvas para o frontend. Ao salvar as informações de data de início e término para qualquer um dos suportes respiratórios, o backend deverá enviar estas informações salvas para o front.

### Critérios de Aceite
- [ ] Enviar informações salvas de data de término para o front - página Suporte respiratório

**Comment by FelipeSVidal** [comment]
Mesmo caso do #199 , porém aqui a data termino não é retornada pelo back, por não ser mais utilizada.
