### ISSUE TITLE
[Back] Remover categoria suporte respiratório

### ISSUE THREAD

**Issue by luannaalves** [EscolaDeSaudePublica/registrocovid-api#209]
### Contexto
As informações contidas na página de suporte respiratório foram migradas para a página Exame físico (renomeada para a página Evolução diária), portanto não deverá existir uma categoria com este nome Suporte respiratório, devendo ser suprimida da página de categorias.

### Escopo
Remover a categoria Suporte respiratório da página de categorias, e conferir se as informações referente ao suporte respiratório na página Evolução diária, está seguindo rota de salvamento para o banco de dados.

### Critérios de Aceite
 - [x] Verificar rota de salvamento das informações de suporte respiratório inseridas na categoria Evolução diária, no banco de dados
- [x] Remover dados da categoria Suporte respiratório da página de categorias no banco de dados.

**Comment by chicaothiago** [comment]
Não é necesssária alterações no vbackend
