### ISSUE TITLE
[Back] Categoria Comorbidades / Condições clínicas

### ISSUE THREAD

**Issue by sluisTW** [EscolaDeSaudePublica/registrocovid-api#24]
Eu como coletador
Quero coletar os dados de Comorbidades das pacientes
Para que possa ser feito o levantamento do agravamento do COVID com base em condições prévias das pacientes

**Contexto**
Comorbidades são questões de saúde pre-existentes nas pacientes, que podem ou não agravar os sintomas da COVID-19.
Para saber ao certo se alguma pre-condição agrava os sintomas, vamos permitir que os coletadores informem estes dados e assim realizar as análises necessárias

**Escopo**
- Criar endpoint para cadastro das Comorbidade / Condições Clínicas de um paciente específico
  - Nenhum dos campos é de informação obrigatória
- Criar endpoint para retornar dados de Comorbidade / Condições Clínicas de um paciente específico
- Lista de doenças
- Lista de "Orgãos"
- Lista de "Corticosteroides"

**Critérios de Aceite**

- [x] **1. Cadastrar Comorbidade / Condições Clínicas com sucesso**
**Dado** que exista paciente previamente cadastrado
**Quando** cadastrar dados de "Comorbidade / Condições Clínicas" corretamente
**Então** "Comorbidade / Condições Clínicas" deverão ser cadastradas com sucesso

- [x] **2. Visualizar dados de Comorbidade / Condições Clínicas previamente cadastrado**
**Dado** exista  paciente com Comorbidade / Condições Clínicas cadastrada
**Quando** buscar dados desta categoria desse paciente
**Então** dados de "Comorbidade / Condições Clínicas" deverão ser retornados com sucesso

3. Retornar dados:
- [x] - Retornar dados da Lista de doenças
- [x] -  Retornar dados da Lista de "Orgãos"
- [x]  - Retornar dados da Lista de "Corticosteroides"

**Checklist**
- [x] Migrations
- [x] Cadastro e listagem tabela comorbidades
- [x] Cadastro e listagem tabelas pivot
- [x] Testes unitários

**Comment by giordanasousa** [comment]
Verificar se faz sentido neste momento, listarmos estaticamente algumas opções (tabelas de cadastro, como: sexo, estado, doenças...), com o objetivo de ganhar velocidade.
As tabelas que estariam estáticas estão em amarelo no modelo de dados (DER) 
@navarrotheus irá verificar com o time.
