### ISSUE TITLE
[Back] Categoria Sintomas Iniciais COVID-19

### ISSUE THREAD

**Issue by sluisTW** [EscolaDeSaudePublica/registrocovid-api#31]
Eu como coletador
Quero colher os sintomas iniciais da paciente
Para poder analisar os dados de outras pacientes e poder ter um diagnóstico mais preciso

**Contexto**
No processo de internação, parte importante é colher os sintomas iniciais da paciente.
Dentro do "Registro Covid", estes dados serão utilizados para poder cruzar os dados das pacientes internadas, tendo um melhor diagnóstico dos pacientes sobre o covid.

**Escopo**
- Criar endpoint para retornar a lista de sintomas iniciais (Dados usados para montar a tela)
- Criar endpoint para **cadastrar** os sintomas iniciais de um paciente
  - Nenhum dos campos é obrigatório
- Criar endpoint para **consultar** os sintomas iniciais de um paciente

**Fora do Escopo**
- Atualizar dados de sintomas Iniciais do paciente
- Cadastrar novo sintoma na lista geral

**Critérios de Aceite**

- [x] **1. Retornar lista de Sintomas padrão da aplicação**
- [x] **2. Cadastrar sintomas iniciais de um paciente com sucesso**
- [x] **3. Consultar sintomas iniciais de um paciente com sucesso**
- [ ] **4. Não permitir cadastrar duas vezes a categoria "Sintomas Iniciais" para o mesmo paciente**

**Comment by navarrotheus** [comment]
A rota implementada para esses dados foi uma rota de atualização, não de cadastro, pois esses dados estão diretamente na tabela de pacientes. Ou seja, foi feita uma rota de atualização da tabela de pacientes que permite atualizar os dados abordados nessa tela.
