### ISSUE TITLE
[Back] Categoria Exames laboratoriais específicos COVID-19

### ISSUE THREAD

**Issue by giordanasousa** [EscolaDeSaudePublica/registrocovid-api#34]
# Descrição

*Como* coletador
*Quero* inserir as informações sobre os Exames laboratoriais específicos dos pacientes com COVID-19
*Para que* possa ser analisada a duração da doença e acompanhar seu desenvolvimento. 

# Contexto
Na página de Categoria dos Exames laboratoriais específicos COVID-19, o coletador poderá inserir as informações referentes ao exame específico de identificação da doença.
**Esse formulário deve se repetir quantas vezes o coletador achar necessário, pois esse exame é realizado várias vezes durante a internação.**

**Os campos presentes neste formulário seguem abaixo:**
- Data coleta RT-PCR 
- Sítio da amostra RT-PCR  Lista de seleção
- Data resultado RT-PCR
- Resultado RT-PCR
- Teste rápido
- Data do teste rápido
- LInk do formulário: https://docs.google.com/forms/d/e/1FAIpQLScez3VY00PsPizKBUBrrScGjr43U3CFU_IonoKJH5oYWN7aOA/formResponse

# Dentro do escopo
- Criar endpoint para cadastro de "Exames laboratoriais específicos COVID-19" de um paciente específico
  - Nenhum dos campos é de informação obrigatória
- Criar endpoint para retornar dados de "Exames laboratoriais específicos COVID-19" de um paciente específico.
- Retornar seeds de sitios
- Retornar lista de resultado de PCR
- A cada novo formulário, criar novo registro.

# Notas
- Apenas o coletador que inseriu o paciente pode incluir informações nos formulários.

# Critério de Aceite

- [x] **1. Cadastrar "Exames laboratoriais específicos COVID-19" com sucesso**
Dado que exista paciente previamente cadastrado
Quando cadastrar dados de "Exames laboratoriais específicos COVID-19" corretamente
Então "Exames laboratoriais específicos COVID-19" deverão ser cadastradas com sucesso

- [x]  **2. Visualizar dados de "Exames laboratoriais específicos COVID-19" previamente cadastrado**
Dado exista paciente com "Exames laboratoriais específicos COVID-19" cadastrada
Quando buscar dados desta categoria desse paciente
Então dados de "Exames laboratoriais específicos COVID-19" deverão ser retornados com sucesso

- [x] **3. Incluir outro exame "Exames laboratoriais específicos COVID-19"
Dado que exista um exame "Exames laboratoriais específicos COVID-19" cadastrado
Quando o coletador precisar incluir outro "Exames laboratoriais específicos COVID-19"
Então o sistema abrirá outro formulário
E os dados serão salvos com outro registro.

- [x] 4. Retornar seeds de sitios

- [x] 5. Retornar lista de resultado de PCR

# Dúvida
- @camilaccolares, os seeds de sitios já foram criados? devemos criar?
- Seeds de resultado de PCR já existem? devemos criar?

**Comment by ferfabricio** [comment]
Desk check realizado, todos os critérios requeridos na task foram atendidos.

@giordanasousa 👍
