### ISSUE TITLE
[Back]Atualizar endpoint que lista municípios e bairros com a opção de filtros

### ISSUE THREAD

**Issue by giordanasousa** [EscolaDeSaudePublica/registrocovid-api#55]
- Atualizar endpoint que lista apenas os municípios para aceitar o filtro de ID do estado
- Resultado final: endpoint trazer os municípios do estado específico de consulta.

- Atualizar o endpoint que lista os bairros para aceitar o filtro do ID do município
- Resultado final: endpoint trazer somente os bairros do município selecionado.

**Comment by ferfabricio** [comment]
@navarrotheus Já fiz as alterações, se puder revisar agradeço!
